version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: hibp
      POSTGRES_USER: hibp
      POSTGRES_PASSWORD: hibp
    ports:
      - "5432:5432"
    networks:
      - hibp_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
  hibp:
    depends_on:
      - postgres
    image: localhost/hibp:latest
    command: [serve, --host=0.0.0.0, '--dsn=postgres://hibp:hibp@postgres:5432/hibp?sslmode=disable']
    restart: unless-stopped
    ports:
      - 15000:15000
    networks:
      - hibp_api
networks:
  hibp_api:

volumes:
  postgres_data: