consumes:
  - application/json
produces:
  - text/plain
schemes:
  - http
  - https
swagger: '2.0'
info:
  description: Self-hosted HIBP password hash checker
  title: Self-hosted HIBP password hash checker
  version: latest
basePath: /
paths:
  /range/{hashPrefix}:
    get:
      description: Search password hashes by range.
      produces:
        - text/plain
      schemes:
        - http
        - https
      tags:
        - range
      operationId: rangeSearch
      parameters:
        - in: path
          name: hashPrefix
          type: string
          required: true
      responses:
        '200':
          description: Request was processed successfully.
          schema:
            type: string
        '400':
          description: Hash prefix must be exactly 5 characters long.
        '404':
          description: No results found.
        '500':
          description: Server encountered an error.
