[global]
    checkNewVersion = false
    sendAnonymousUsage = false

[entryPoints]
    [entryPoints.hibp-http]
        address = ":80"
        # [entryPoints.hibp-http.http.redirections.entryPoint]
        #     # Once the first certificate has been resolved, you can uncomment this section
        #     # to get an automatic http -> https redirect.
        #     to = "hibp-https"
        #     scheme = "https"
        #     permanent = false
    [entryPoints.hibp-https]
        address = ":443"

[providers]
    [providers.docker]
        exposedByDefault = false

[log]
    level = "TRACE"
    format = "common"

[api]
    insecure = true
    dashboard = true

[certificatesResolvers.hibp-certresolver.acme]
    # Email address used for registration.
    email = "email@example.com"
    # File used for the certificate storage.
    # Please keep in mind, this file is stored on a Docker mounted volume.
    # This path is the in-container path only.
    storage = "/etc/acme/acme.json"
    
    # CA server to use.
    # Uncomment the line to use Let's Encrypt's staging server,
    # leave commented to go to prod.
    #
    # Optional
    # Default: "https://acme-v02.api.letsencrypt.org/directory"
    #
    # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

    # KeyType to use.
    # Uses the default value. Other available options: "EC256", "EC384", "RSA2048", "RSA4096", "RSA8192".
    keyType = "RSA4096"

    # Once the first http challenge has been executed, you can uncomment the setting below to use
    # the TLS-ALPN-01 challenge.
    # [certificatesResolvers.hibp-certresolver.acme.tlsChallenge]

    [certificatesResolvers.hibp-certresolver.acme.httpChallenge]
        # EntryPoint to use for the HTTP-01 challenges.
        # Required.
        entryPoint = "hibp-http"