version: '3.3'

services:
  postgres:
    image: postgres:9.6.17
    restart: unless-stopped
    environment:
      POSTGRES_DB: hibp
      POSTGRES_USER: hibp
      POSTGRES_PASSWORD: hibp
    ports:
      - "5432:5432"
    networks:
      - hibpexample
  hibp:
    depends_on:
      - postgres
    image: localhost/hibp:latest
    command: [serve, --host=0.0.0.0]
    restart: unless-stopped
    ports:
      - 15000:15000
    networks:
      - hibpexample
networks:
  hibpexample: