version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: hibp
      POSTGRES_USER: hibp
      POSTGRES_PASSWORD: hibp
    ports:
      - "5432:5432"
    networks:
      - hibpexample
  hibp:
    depends_on:
      - postgres
    image: localhost/hibp:latest
    command: [serve, --host=0.0.0.0, '--dsn=postgres://hibp:hibp@postgres:5432/hibp?sslmode=disable']
    restart: unless-stopped
    ports:
      - 15000:15000
    labels:
      - traefik.enable=true
      - traefik.http.routers.hibp.rule=Host(`your-hibp-api.example.com`)
      - traefik.http.routers.hibp.entrypoints=hibp-https
      - traefik.http.routers.hibp.service=hibp-svc
      - traefik.http.routers.hibp.tls.certResolver=hibp-certresolver
      - traefik.http.services.hibp-svc.loadbalancer.server.port=15000
    networks:
      - hibpexample
networks:
  hibpexample: