version: '3.3'

services:
  traefik:
    image: traefik:2.4.8
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./etc/acme:/etc/acme:rw
    networks:
      - hibpexample
networks:
  hibpexample: